version: "2017-09-20"
pipeline:
  - id: build
    type: script
    overlay: ci/python
    commands:
    - desc: "Install dependencies"
      cmd: |
        pip install -r requirements.txt
        pip install coveralls codecov
    - desc: "Run Tests"
      cmd: python3 setup.py test
    - desc: "Check code style"
      cmd: python3 setup.py flake8
    - desc: "Build docker image that will upload package"
      cmd: |
        VERSION=$(./next-version)

        if [[ -z "${CDP_PULL_REQUEST_NUMBER}" ]]; then
          DOCKER_IMAGE="pierone.stups.zalan.do/teapot/sevenseconds-release:${CDP_TARGET_REPOSITORY_COUNTER}"
        else
          DOCKER_IMAGE="pierone.stups.zalan.do/teapot/sevenseconds-release-pr:${CDP_TARGET_REPOSITORY_COUNTER}"
        fi

        docker build --build-arg VERSION="$VERSION" -t "$DOCKER_IMAGE" .

        docker push "$DOCKER_IMAGE"

        if [[ -z "${CDP_PULL_REQUEST_NUMBER}" ]]; then
            git log -1 --pretty=%B > CHANGELOG
            # TODO upload the wheel package
            git gh-release --message-from-file CHANGELOG $VERSION
        fi
        # The actual release is done by a pipeline in Zalando's Internal Github Enterprise
